#!/bin/bash

echo
echo Plese chose the option from below
echo
echo 'a = Display date and time'
echo
echo 'b = list file and directories'
echo
echo 'c = list user logged in'
echo
echo 'd = check system uptime'
echo
        read choices
        case $choices in

a) date;;
b) ls;;
c) who;;
d) uptime;;
*) echo invilad choices - bye.
        esac
